### ISSUE TITLE
DONATE Link broken?

### ISSUE THREAD

**Issue by gogene** [gobridge/about-us#3]
Hi, I'm not able to donate from a German Paypal Account.
Maybe the Link is broken?

**Comment by ardan-bkennedy** [comment]
Let me ask BridgeFoundry. Sorry for the inconvenience and thanks for the support.

**Comment by ardan-bkennedy** [comment]
I guess the link I was using was based on a session :(. My only choice was to link to a BF page that had a form based link that works. Thanks for pointing this out!
