### ISSUE TITLE
Win a 100% Scholarship on this International Women’s Day  

### ISSUE THREAD

**Issue by mmadition** [gobridge/about-us#4]
The International Women’s day 2019 was celebrated with huge excitement. All the leading brand's retail stores, eCommerce stores had showered much-privileged offers on the ladies around the world. JanBask Training- an e-learning platform had launched a scholarship contest. The winners of this contest stand a chance to win exciting Scholarships right up to 100% on Live Training in selected courses. 
JanBask Training- a leading e-learning platform has joined the league of pushing for women’s rights and equality, as they are out there running a scholarship contest that had started on this year’s International Women’s day. Lucky winners of this contest will get free online training in selected courses.
This scholarship is a chance for all the women who really want to make a difference in their careers. The amazing scholarships can easily be availed by simply registering for the contest with an email address and selecting the relevant course category. Thereafter, the registrant can answer the contest questions upon receiving an email on their registered email id.  For more details, visit: 
https://www.janbasktraining.com/international-womens-day-scholarship
Winning this scholarship program can be a big breakthrough. Here are a few details of the Scholarship program-
Men can refer their women friend, wife, sister or colleague in this contest and their friend can take the contest from there. 
Only one application per student is allowed.
The contest will run from 8th March 2019 to 29.03.2019. 
The company will announce the results on 30.03.2019 
The first lucky winner will get a 100% scholarship on anyone online training course.
Two Lucky winners will get 100% Scholarship on anyone online self-paced training course.
Five Lucky Winners will get a 50% scholarship on anyone online training.
Note: All the prizes are applicable to the following courses only: Quality Assurance Testing, Business Analyst, SQL Server, Java, DevOps, AWS and Salesforce Admin & Developer.
Mr. Tarun Arora, the energetic Vice President of the company elaborated a little on this offer. He said that- “We have seen an overwhelming response, so far in this contest. So many women have already enrolled. We want to see more and more women register and benefit from this great opportunity.” Mr. Arora highlighted a few features that these courses. Let us take a look at them-
All the sessions at JanBask Training are conducted in a live environment
The learners are groomed in a collaborative ecosystem of learning
Self-assessment quizzes, live debates are a part of a learner’s daily routines
All the courses contain comprehensive training modules that cover practical and theoretical training
The learning is supported with a varied and interesting range of learning resources that keep the interest of the learners intact
Learners get to study the Agile Methodologies associated with every course so that they get up-to-date and industry-oriented training.
The contest had started on March 8th, register now to avail this once in a lifetime opportunity
The registration process is given here 
https://www.janbasktraining.com/international-womens-day-scholarship
About JanBask Training- JanBask Training is an online training platform that is committed to providing quality online training at very affordable prices to learners across the world. All the courses are designed after taking into consideration the job patterns of the market, certification guidelines and industry standards.

**Comment by ardan-bkennedy** [comment]
Hello and thank you for the message. Unfortunately, this isn’t the appropriate place for sharing information like this. I will have to close this issue.
